// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYJj7KXfUYJGncIVo_Kkj22eEtIVnfzqA',
    appId: '1:818033328183:web:600bcb0ed75a1364dd3fb2',
    messagingSenderId: '818033328183',
    projectId: 'stackup-841df',
    authDomain: 'stackup-841df.firebaseapp.com',
    storageBucket: 'stackup-841df.appspot.com',
    measurementId: 'G-502WGLZLJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlSh39i7ZD3NpeicpbvnoT9E5XggTrsQ8',
    appId: '1:818033328183:android:295bcd1d5ba906f2dd3fb2',
    messagingSenderId: '818033328183',
    projectId: 'stackup-841df',
    storageBucket: 'stackup-841df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjPtIQaRbWDq4ySZWvcCoFb6JGoVqV7ho',
    appId: '1:818033328183:ios:37cd6aee2a80e648dd3fb2',
    messagingSenderId: '818033328183',
    projectId: 'stackup-841df',
    storageBucket: 'stackup-841df.appspot.com',
    iosBundleId: 'com.example.stackupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjPtIQaRbWDq4ySZWvcCoFb6JGoVqV7ho',
    appId: '1:818033328183:ios:37cd6aee2a80e648dd3fb2',
    messagingSenderId: '818033328183',
    projectId: 'stackup-841df',
    storageBucket: 'stackup-841df.appspot.com',
    iosBundleId: 'com.example.stackupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYJj7KXfUYJGncIVo_Kkj22eEtIVnfzqA',
    appId: '1:818033328183:web:0407337dbc87ce20dd3fb2',
    messagingSenderId: '818033328183',
    projectId: 'stackup-841df',
    authDomain: 'stackup-841df.firebaseapp.com',
    storageBucket: 'stackup-841df.appspot.com',
    measurementId: 'G-TQV55N6YG8',
  );

}